apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mycompany.fullname" . }}-map
data:
  web01.conf: |
    server {
    listen      {{ .Values.httpport }};
    server_name  {{ .Values.web1 }};

    #charset koi8-r;
    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        root   /etc/nginx/conf.d/web01/;
        index  index.html index.htm;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
    }
  index1.html: |
    <h1>This is Web 1 </h1>
  web02.conf: |
    server {
    listen       {{ .Values.httpport }};
    server_name  {{ .Values.web2 }};

    #charset koi8-r;
    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        root   /etc/nginx/conf.d/web02/;
        index  index.html index.htm;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
    }
  index2.html: |
    <h1>This is Web 2 </h1>