apiVersion: v1
kind: Service
metadata:
  name: {{ include "mycompany.fullname" . }}-proxysvc
  labels:
    app: {{ .Chart.Name }}
    tier: {{ .Values.proxytier }}
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: {{ .Values.proxyport }}
  selector:
    app: {{ .Chart.Name }}
    tier: {{ .Values.proxytier }}