apiVersion: v1
kind: Service
metadata:
  name: {{ include "mycompany.fullname" . }}-websvc
  labels:
    app: {{ .Chart.Name }}
spec:
  type: LoadBalancer  
  # type: NodePort  
  ports:
  - protocol: TCP
    port: {{ .Values.httpport }}
  selector:
    app: {{ .Chart.Name }}
    tier: {{ .Values.webtier }}


  # type: LoadBalancer  
  # ports:
  # - protocol: TCP
  #   port: {{ .Values.httpport }}
  #   targetPort: {{ .Values.httpport }}
  # selector:
  #   app: {{ .Chart.Name }}
  #   tier: {{ .Values.webtier }}