apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
  name: denny-storage-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole  #this must be Role or ClusterRole
  name: storage-admin  # this must match the name of the Role or ClusterRole you wish to bind to
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: denny
  kind: Group
  name: admin