apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T18:52:05Z
  name: var-configmap
  namespace: default

data:
  COLOR: "blue"
  STATUS: "running"
  game.properties: |
    enemies=aliens
    lives=3