apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxpod
  name: podwithconfigmap
spec:
  containers:
  - image: nginx
    name: nginxpod
    envFrom:
    - configMapRef:
        name: sample-configmap
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}