apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: podwith-envvar
spec:
  containers:
  - image: nginx
    name: nginxpod
    env:
    - name: SURNAME
      value: Vettom

    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

