apiVersion: v1
data:
  pass1: bmV3cGFzcwo=
kind: Secret
metadata:
  creationTimestamp: "2019-11-13T15:16:51Z"
  name: newsecret
  namespace: default
  resourceVersion: "1311100"
  selfLink: /api/v1/namespaces/default/secrets/mytestsecret
  uid: aa0b268f-2270-41ab-9195-be82ae549bdb
type: Opaque
