apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volumes
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:  # At same level are capacity
    path: /tmp


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-log-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Mi



#  Adding claim to Pod. ****---- Note here  persistentvoume us starting in lower case
  # volumes:
  # - name: webapp
  #   persistentVolumeClaim:
  #     claimName: claim-log-1